openapi: 3.0.0
info:
  title: Wallet API
  version: 1.0.0
  description: REST API for wallet management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
